### ISSUE TITLE
我想配合ik使用，配置后发现并没有起作用

### ISSUE THREAD

**Issue by conanJiang** [dowenliu-xyz/elasticsearch-analysis-token-filter-pinyin#1]
配置项如下：

 index:
  analysis:
    filter:
       pinyin:
         type: pinyin
         transformType: 1
         keepOrigin: true
         minTermLength: 2
    analyzer:
      ik:
        alias:
        - ik_analyzer
        type: ik
      ik_max_word:
        type: ik
        use_smart: false
      ik_smart:
        type: ik
        use_smart: true
      ik_max_word_pinyin:
        type: ik
        use_smart: false
        filter:
        - pinyin
      ik_smart_pinyin:
        type: ik
        use_smart: true
        filter:
        - pinyin

 index.analysis.analyzer.default.type: ik

打成插件包也能识别到pinyin插件

**Comment by dowenliu-xyz** [comment]
刚从Solr切到ES里，没在ES里用过IK。。。。。。
而且，我是使用创建index时配置Analyzer的，你可以试试在index的settings里配置试试。
在yml里配置的问题，我需要研究下

**Comment by dowenliu-xyz** [comment]
好吧，我已经知道问题了，你的配置是有问题的。加pinyin过滤器的Analyzer是自定义的，需要type: custom：

```
index:
    analysis:
        filter:
            pinyin:
                type: pinyin
                transformType: 1
                keepOrigin: false
                minTermLength: 2
        analyzer:
            ik:
                alias:
                    - ik_analyzer
                type: ik
            ik_max_word:
                type: ik
                use_smart: false
            ik_smart:
                type: ik
                use_smart: true
            ik_max_word_pinyin:
                type: custom
                tokenizer: ik_max_word
                filter:
                    - pinyin
            ik_smart_pinyin:
                type: custom
                tokenizer: ik_smart
                filter:
                    - pinyin
```
